<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Test" Id="{e29f903d-7e37-4dfb-b7bc-faafdeb7da7a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Test IMPLEMENTS I_Test
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="METH" Id="{9f908876-f844-416e-b279-14bd21525fed}">
      <Declaration><![CDATA[METHOD METH : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Name" Id="{a014e8f7-c5f0-4d75-be2e-cb82d3e30fd2}">
      <Declaration><![CDATA[PROPERTY Name : STRING
]]></Declaration>
      <Get Name="Get" Id="{5ddd5ea9-6be2-4269-927b-8df3085c5ff5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'Test';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>